services:

  # ==============================
  # FastAPI Backend
  # ==============================

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: cloud-backend

    environment:
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/cloud_pipeline
      REDIS_URL: redis://redis:6379/0

    env_file:
      - .env

    depends_on:
      - postgres

    networks:
      - app-network

    restart: unless-stopped


  # ==============================
  # React + Nginx
  # ==============================

  frontend:
    build:
      context: .
      dockerfile: nginx/Dockerfile

    container_name: image_rag_frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped


  postgres:
    image: postgres:16

    container_name: cloud-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cloud_pipeline

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge



